[package]
name = "ipv6addr"
version = "0.1.0"
edition = "2024"
authors = ["Michel Boucey <michel.boucey@gmail.com>"]
license = "BSD-3-Clause"
categories = ["Network programming","command-line-utilities"]
keywords = ["network","ipv6", "cli"]
description = "A library to deal with IPv6 address text representations, canonization and manipulations."
homepage = "https://github.com/MichelBoucey/ipv6addr-rs"
repository = "https://github.com/MichelBoucey/ipv6addr-rs"
readme = "README.md"

[dependencies]
itertools = "0.15.0"
smallvec = "1.16.1"
